version: "3.2"
services:
  flip-eth-a:
    build: .
    image: makerdao/auction-keeper
    container_name: flip-eth-a
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/flip/eth-a/flip-eth-a.sh:/opt/keeper/flip-eth-a.sh
      - $PWD/flip/eth-a/model-eth.sh:/opt/keeper/model-eth.sh
      - $PWD/env/:/opt/keeper/env/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: /opt/keeper/flip-eth-a.sh model-eth.sh
  flop:
    build: .
    image: makerdao/auction-keeper
    container_name: flop
    volumes:
      - $PWD/secrets:/opt/keeper/secrets
      - $PWD/flop/flop.sh:/opt/keeper/flop.sh
      - $PWD/flop/model-mkr.sh:/opt/keeper/model-mkr.sh
      - $PWD/env/:/opt/keeper/env/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: /opt/keeper/flop.sh model-mkr.sh
